import LegalPageLayout, { Section, ExtLink } from '@/components/LegalPageLayout';
import { usePageMeta } from '@/lib/usePageMeta';
import { site } from '@/data/site';

const LAST_UPDATED = site.legalUpdated;

export default function Disclaimer() {
  usePageMeta({
    title: 'Disclaimer | ToolKit',
    description:
      'Important disclaimers for ToolKit free online tools, including accuracy of results, the BMI calculator, external links, advertising and limitation of liability.',
    keywords: 'disclaimer, accuracy, no warranty, BMI disclaimer, external links, advertising disclosure',
    path: '/disclaimer',
  });

  return (
    <LegalPageLayout
      title="Disclaimer"
      lastUpdated={LAST_UPDATED}
      intro={
        <>
          The information and tools on this website are provided for general
          informational purposes only. By using ToolKit you acknowledge and agree
          to the disclaimers set out below. Please read them carefully.
        </>
      }
    >
      <Section title="1. General Information Only">
        <p>
          All content, calculators, converters and utilities on this website are
          provided in good faith and for general information and convenience
          purposes only. While we aim for accuracy, we make no representation or
          warranty of any kind, express or implied, regarding the accuracy,
          adequacy, validity, reliability, availability or completeness of any
          information, tool output or result produced by this website.
        </p>
      </Section>

      <Section title="2. Verify Before You Rely on It">
        <p>
          Tool results are generated by client-side code running in your browser.
          You are solely responsible for independently verifying any output
          before acting on it. Do not rely on this website for decisions with
          legal, financial, medical, safety or other significant consequences.
        </p>
      </Section>

      <Section title="3. Health and Medical Disclaimer">
        <p>
          Our BMI calculator and any other health-related tool is provided for
          general educational purposes only. It is <strong>not</strong> a medical
          device and does not constitute medical advice, diagnosis or treatment,
          and it is not a substitute for consultation with a qualified
          healthcare professional. BMI is a simplified screening measure that
          does not account for factors such as muscle mass, age, sex, body
          composition or medical conditions.
        </p>
        <p>
          Always seek the advice of a physician or other qualified health
          provider with any questions about a medical condition or before
          starting, changing or stopping any health-related programme. Never
          disregard professional medical advice because of something you have
          read or calculated on this website.
        </p>
      </Section>

      <Section title="4. Security and Password Tools">
        <p>
          Our password generator creates random values using your browser&apos;s
          cryptographic random number generator. However, we cannot guarantee
          that any password generated will be suitable for, or sufficient to
          protect, any particular system or account. You are responsible for
          following the password policies of the services you use and for
          storing and managing your credentials securely.
        </p>
      </Section>

      <Section title="5. Development and Technical Tools">
        <p>
          Developer utilities such as the color converter and case converter are
          provided as convenience aids. Always validate generated values, colour
          codes, formatting and converted units in your own environment before
          using them in production systems.
        </p>
      </Section>

      <Section title="6. External Links Disclaimer">
        <p>
          This website may contain links to external websites or content
          originating from third parties. We do not investigate, monitor or check
          such external links for accuracy, adequacy, validity, reliability,
          availability or completeness. We do not warrant, endorse, guarantee or
          assume responsibility for the accuracy or reliability of any
          information offered by third-party websites, and we are not a party to
          — and accept no responsibility for — any transaction you may enter into
          with third-party providers.
        </p>
      </Section>

      <Section title="7. Advertising Disclaimer">
        <p>
          This website is supported by advertising, including advertisements
          served through Google AdSense and other third-party advertising
          partners. Advertisements are not endorsements. We do not control which
          specific ads are shown, and the appearance of an advertisement on this
          website does not constitute a recommendation of the advertiser, its
          products or its services.
        </p>
        <p>
          We are not responsible for any loss or damage incurred as a result of
          dealings with advertisers found on or through this website. See our{' '}
          <a href="/privacy-policy" className="text-brand-600 underline hover:text-brand-700">
            Privacy Policy
          </a>{' '}
          for information on advertising cookies and how to opt out of
          personalised advertising.
        </p>
      </Section>

      <Section title="8. Errors and Omissions">
        <p>
          The website may contain typographical errors, inaccuracies or
          omissions. We reserve the right to correct any errors, inaccuracies or
          omissions, and to change or update information at any time without
          prior notice. See our{' '}
          <a href="/terms" className="text-brand-600 underline hover:text-brand-700">
            Terms of Service
          </a>{' '}
          for the full terms governing use of the website.
        </p>
      </Section>

      <Section title="9. No Financial or Legal Advice">
        <p>
          Nothing on this website constitutes financial, investment, accounting,
          tax or legal advice. Before making any financial or legal decision,
          consult a licensed professional in your jurisdiction.
        </p>
      </Section>

      <Section title="10. Consent and Updates">
        <p>
          By using this website you consent to this disclaimer and agree to its
          terms. We may update this disclaimer from time to time; the revised
          version will be posted on this page with a new &quot;Last updated&quot;
          date. Continued use of the website after changes are posted constitutes
          acceptance of those changes.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          If you have questions about this disclaimer, please contact us via our{' '}
          <a href="/contact" className="text-brand-600 underline hover:text-brand-700">
            Contact page
          </a>{' '}
          or by email at{' '}
          <ExtLink href="mailto:support@toolkit-tools.pages.dev">
            support@toolkit-tools.pages.dev
          </ExtLink>
          .
        </p>
      </Section>
    </LegalPageLayout>
  );
}
